// GPU参数数据
const gpuData = [
    {
        id: 1,
        vendor: "NVIDIA",
        architecture: "Volta",
        model: "V100 SXM2",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 7.80,
        fp32TFlops: 15.70,
        fp16TensorCoreTFlops: 125.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: null,
        memorySizeGB: 32,
        memoryType: "HBM2",
        memoryBandwidthGBs: 900.00,
        memoryBusWidth: "4096-bit",
        interCardConnection: "300GB/s",
        pcieConnection: "PCIe Gen3x16: 32GB/s",
        maxPowerW: 300
    },
    {
        id: 2,
        vendor: "NVIDIA",
        architecture: "Turing",
        model: "RTX 6000",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 8.20,
        fp16TensorCoreTFlops: 65.30,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 130.50,
        memorySizeGB: 24,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 672.00,
        memoryBusWidth: "384-bit",
        interCardConnection: "",
        pcieConnection: "",
        maxPowerW: 260
    },
    {
        id: 3,
        vendor: "NVIDIA",
        architecture: "Turing",
        model: "T4",
        mainScenes: ["推理", "渲染", "编解码"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 8.10,
        fp16TensorCoreTFlops: 65.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 130.00,
        memorySizeGB: 16,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 320.00,
        memoryBusWidth: "256-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen3x16: 32GB/s",
        maxPowerW: 70
    },
    {
        id: 4,
        vendor: "NVIDIA",
        architecture: "Turing",
        model: "2080",
        mainScenes: ["渲染"],
        type: "渲染",
        fp64TFlops: null,
        fp32TFlops: 10.60,
        fp16TensorCoreTFlops: 84.80,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 169.60,
        memorySizeGB: 8,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 448.00,
        memoryBusWidth: "352-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen3x16: 32GB/s",
        maxPowerW: 225
    },
    {
        id: 5,
        vendor: "NVIDIA",
        architecture: "Turing",
        model: "2080 Ti",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 14.20,
        fp16TensorCoreTFlops: 113.80,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 227.70,
        memorySizeGB: 11,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 616.00,
        memoryBusWidth: "352-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen3x16: 32GB/s",
        maxPowerW: 260
    },
    {
        id: 6,
        vendor: "NVIDIA",
        architecture: "Turing",
        model: "2080 Super",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 11.20,
        fp16TensorCoreTFlops: 89.20,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 178.40,
        memorySizeGB: 8,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 496.00,
        memoryBusWidth: "256-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen3x16: 32GB/s",
        maxPowerW: 250
    },
    {
        id: 7,
        vendor: "NVIDIA",
        architecture: "Ampere",
        model: "3070",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: null,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: null,
        memorySizeGB: 8,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 448.00,
        memoryBusWidth: "256 bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 220
    },
    {
        id: 8,
        vendor: "NVIDIA",
        architecture: "Ampere",
        model: "3080",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 29.80,
        fp16TensorCoreTFlops: 59.50,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 238.00,
        memorySizeGB: 10,
        memoryType: "GDDR6X",
        memoryBandwidthGBs: 760.30,
        memoryBusWidth: "320 bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 320
    },
    {
        id: 9,
        vendor: "NVIDIA",
        architecture: "Ampere",
        model: "3090",
        mainScenes: ["训练", "推理", "渲染"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: 35.58,
        fp16TensorCoreTFlops: 142.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: null,
        memorySizeGB: 24,
        memoryType: "GDDR6X",
        memoryBandwidthGBs: 936.00,
        memoryBusWidth: "384-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 350
    },
    {
        id: 10,
        vendor: "NVIDIA",
        architecture: "Ampere",
        model: "RTX A6000",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: 1.21,
        fp32TFlops: 38.71,
        fp16TensorCoreTFlops: 154.80,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 309.70,
        memorySizeGB: 48,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 768.00,
        memoryBusWidth: "384-bit",
        interCardConnection: "",
        pcieConnection: "",
        maxPowerW: null
    },
    {
        id: 11,
        vendor: "NVIDIA",
        architecture: "Ampere",
        model: "A40",
        mainScenes: ["训练", "推理", "渲染"],
        type: "训练",
        fp64TFlops: 0.58,
        fp32TFlops: 37.40,
        fp16TensorCoreTFlops: 149.70,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 299.30,
        memorySizeGB: 48,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 696.00,
        memoryBusWidth: "384-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 300
    },
    {
        id: 12,
        vendor: "NVIDIA",
        architecture: "Ampere",
        model: "A100-80G SXM",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 19.50,
        fp32TFlops: 19.50,
        fp16TensorCoreTFlops: 312.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 624.00,
        memorySizeGB: 80,
        memoryType: "HBM2e",
        memoryBandwidthGBs: 2039.00,
        memoryBusWidth: "5120-bit",
        interCardConnection: "600GB/s",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 400
    },
    {
        id: 13,
        vendor: "NVIDIA",
        architecture: "Ampere",
        model: "A10",
        mainScenes: ["推理", "渲染", "编解码"],
        type: "推理",
        fp64TFlops: 0.98,
        fp32TFlops: 31.24,
        fp16TensorCoreTFlops: 125.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 250.00,
        memorySizeGB: 24,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 600.00,
        memoryBusWidth: "384-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 150
    },
    {
        id: 14,
        vendor: "NVIDIA",
        architecture: "Ampere",
        model: "A30",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 10.30,
        fp32TFlops: 10.30,
        fp16TensorCoreTFlops: 165.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 330.00,
        memorySizeGB: 24,
        memoryType: "HBM2",
        memoryBandwidthGBs: 933.00,
        memoryBusWidth: "",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 165
    },
    {
        id: 15,
        vendor: "NVIDIA",
        architecture: "Ampere",
        model: "3080 Ti",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: 136.40,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 272.80,
        memorySizeGB: 12,
        memoryType: "GDDR6X",
        memoryBandwidthGBs: 912.00,
        memoryBusWidth: "384-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 350
    },
    {
        id: 16,
        vendor: "NVIDIA",
        architecture: "Ampere",
        model: "A100-80G PCIe",
        mainScenes: ["推理"],
        type: "推理",
        fp64TFlops: 19.50,
        fp32TFlops: 19.50,
        fp16TensorCoreTFlops: 312.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 624.00,
        memorySizeGB: 80,
        memoryType: "HBM2e",
        memoryBandwidthGBs: 1935.00,
        memoryBusWidth: "5120-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 300
    },
    {
        id: 17,
        vendor: "NVIDIA",
        architecture: "Ampere",
        model: "3090 Ti",
        mainScenes: ["训练", "推理", "渲染"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: 40.00,
        fp16TensorCoreTFlops: 160.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 320.00,
        memorySizeGB: 24,
        memoryType: "GDDR6X",
        memoryBandwidthGBs: 1008.00,
        memoryBusWidth: "384-bit",
        interCardConnection: "不支持",
        pcieConnection: "",
        maxPowerW: 450
    },
    {
        id: 18,
        vendor: "NVIDIA",
        architecture: "Ampere",
        model: "A800",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 9.70,
        fp32TFlops: 19.50,
        fp16TensorCoreTFlops: 312.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 624.00,
        memorySizeGB: 80,
        memoryType: "HBM2e",
        memoryBandwidthGBs: 2039.00,
        memoryBusWidth: "5120-bit",
        interCardConnection: "400GB/s",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 400
    },
    {
        id: 19,
        vendor: "NVIDIA",
        architecture: "Ada Lovelace",
        model: "4080",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 48.70,
        fp16TensorCoreTFlops: 194.90,
        fp8TensorCoreTFlops: 389.90,
        int8TensorCoreTOps: 389.90,
        memorySizeGB: 16,
        memoryType: "GDDR6X",
        memoryBandwidthGBs: 716.80,
        memoryBusWidth: "256-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 320
    },
    {
        id: 20,
        vendor: "NVIDIA",
        architecture: "Ada Lovelace",
        model: "4090",
        mainScenes: ["训练", "推理", "渲染"],
        type: "训练",
        fp64TFlops: 1.29,
        fp32TFlops: 82.60,
        fp16TensorCoreTFlops: 330.30,
        fp8TensorCoreTFlops: 660.60,
        int8TensorCoreTOps: 660.60,
        memorySizeGB: 24,
        memoryType: "GDDR6X",
        memoryBandwidthGBs: 1008.00,
        memoryBusWidth: "384-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 450
    },
    {
        id: 21,
        vendor: "NVIDIA",
        architecture: "Ada Lovelace",
        model: "L40",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: 1.41,
        fp32TFlops: 90.50,
        fp16TensorCoreTFlops: 181.00,
        fp8TensorCoreTFlops: 362.00,
        int8TensorCoreTOps: 362.00,
        memorySizeGB: 48,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 864.00,
        memoryBusWidth: "384-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 300
    },
    {
        id: 22,
        vendor: "NVIDIA",
        architecture: "Ada Lovelace",
        model: "4090D",
        mainScenes: ["训练", "推理", "渲染"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: 73.50,
        fp16TensorCoreTFlops: 294.20,
        fp8TensorCoreTFlops: 588.00,
        int8TensorCoreTOps: 588.00,
        memorySizeGB: 24,
        memoryType: "GDDR6X",
        memoryBandwidthGBs: 1008.00,
        memoryBusWidth: "384-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 425
    },
    {
        id: 23,
        vendor: "NVIDIA",
        architecture: "Ada Lovelace",
        model: "L4",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 30.30,
        fp16TensorCoreTFlops: 121.00,
        fp8TensorCoreTFlops: 242.50,
        int8TensorCoreTOps: 242.50,
        memorySizeGB: 24,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 300.00,
        memoryBusWidth: "192-bit",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 72
    },
    {
        id: 24,
        vendor: "NVIDIA",
        architecture: "Ada Lovelace",
        model: "L40S",
        mainScenes: ["训练", "推理", "渲染"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: 91.60,
        fp16TensorCoreTFlops: 362.05,
        fp8TensorCoreTFlops: 733.00,
        int8TensorCoreTOps: 733.00,
        memorySizeGB: 48,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 864.00,
        memoryBusWidth: "",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 350
    },
    {
        id: 25,
        vendor: "NVIDIA",
        architecture: "Ada Lovelace",
        model: "L2",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 24.10,
        fp16TensorCoreTFlops: 96.50,
        fp8TensorCoreTFlops: 193.00,
        int8TensorCoreTOps: 193.00,
        memorySizeGB: 24,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 300.00,
        memoryBusWidth: "",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 72
    },
    {
        id: 26,
        vendor: "NVIDIA",
        architecture: "Ada Lovelace",
        model: "L20",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 59.30,
        fp16TensorCoreTFlops: 119.00,
        fp8TensorCoreTFlops: 237.00,
        int8TensorCoreTOps: 237.00,
        memorySizeGB: 48,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 864.00,
        memoryBusWidth: "",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 275
    },
    {
        id: 27,
        vendor: "NVIDIA",
        architecture: "Hopper",
        model: "H800 SXM",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 1.00,
        fp32TFlops: 67.00,
        fp16TensorCoreTFlops: 989.50,
        fp8TensorCoreTFlops: 1979.00,
        int8TensorCoreTOps: 1979.00,
        memorySizeGB: 80,
        memoryType: "HBM3",
        memoryBandwidthGBs: 3350.00,
        memoryBusWidth: "",
        interCardConnection: "400GB/s Switch",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 700
    },
    {
        id: 28,
        vendor: "NVIDIA",
        architecture: "Hopper",
        model: "H100 SXM",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 34.00,
        fp32TFlops: 67.00,
        fp16TensorCoreTFlops: 989.50,
        fp8TensorCoreTFlops: 1979.00,
        int8TensorCoreTOps: 1979.00,
        memorySizeGB: 80,
        memoryType: "HBM3",
        memoryBandwidthGBs: 3350.00,
        memoryBusWidth: "",
        interCardConnection: "900GB/s Switch",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 700
    },
    {
        id: 29,
        vendor: "NVIDIA",
        architecture: "Hopper",
        model: "H100 PCIe",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 26.00,
        fp32TFlops: 51.00,
        fp16TensorCoreTFlops: 756.50,
        fp8TensorCoreTFlops: 1513.00,
        int8TensorCoreTOps: 1513.00,
        memorySizeGB: 80,
        memoryType: "HBM2e",
        memoryBandwidthGBs: 2000.00,
        memoryBusWidth: "",
        interCardConnection: "600GB/s Bridge",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 350
    },
    {
        id: 30,
        vendor: "NVIDIA",
        architecture: "Hopper",
        model: "H100 NVL",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 68.00,
        fp32TFlops: 134.00,
        fp16TensorCoreTFlops: 1979.00,
        fp8TensorCoreTFlops: 3958.00,
        int8TensorCoreTOps: 3958.00,
        memorySizeGB: 188,
        memoryType: "",
        memoryBandwidthGBs: 7200.00,
        memoryBusWidth: "",
        interCardConnection: "600GB/s Bridge",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 800
    },
    {
        id: 31,
        vendor: "NVIDIA",
        architecture: "Hopper",
        model: "H200 SXM",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 34.00,
        fp32TFlops: 67.00,
        fp16TensorCoreTFlops: 1979.00,
        fp8TensorCoreTFlops: 3958.00,
        int8TensorCoreTOps: 3958.00,
        memorySizeGB: 141,
        memoryType: "HBM3e",
        memoryBandwidthGBs: 4800.00,
        memoryBusWidth: "",
        interCardConnection: "900GB/s Switch",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: null
    },
    {
        id: 32,
        vendor: "NVIDIA",
        architecture: "Hopper",
        model: "H20-96G",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 1.00,
        fp32TFlops: 44.00,
        fp16TensorCoreTFlops: 148.00,
        fp8TensorCoreTFlops: 296.00,
        int8TensorCoreTOps: 296.00,
        memorySizeGB: 96,
        memoryType: "HBM3",
        memoryBandwidthGBs: 4000.00,
        memoryBusWidth: "",
        interCardConnection: "900GB/s Switch",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 500
    },
    {
        id: 33,
        vendor: "NVIDIA",
        architecture: "Hopper",
        model: "H20-141G",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 1.00,
        fp32TFlops: 44.00,
        fp16TensorCoreTFlops: 148.00,
        fp8TensorCoreTFlops: 296.00,
        int8TensorCoreTOps: 296.00,
        memorySizeGB: 141,
        memoryType: "HBM3e",
        memoryBandwidthGBs: 4800.00,
        memoryBusWidth: "",
        interCardConnection: "900GB/s Switch",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 500
    },
    {
        id: 34,
        vendor: "NVIDIA",
        architecture: "Blackwell",
        model: "B200 DGX",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 37.00,
        fp32TFlops: 75.00,
        fp16TensorCoreTFlops: 4500.00,
        fp8TensorCoreTFlops: 9000.00,
        int8TensorCoreTOps: 9000.00,
        memorySizeGB: 180,
        memoryType: "HBM3e",
        memoryBandwidthGBs: 7700.00,
        memoryBusWidth: "",
        interCardConnection: "NVLink 1.8TB/s",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 1000
    },
    {
        id: 35,
        vendor: "NVIDIA",
        architecture: "Blackwell",
        model: "B100 DGX",
        mainScenes: [],
        type: "",
        fp64TFlops: 30.00,
        fp32TFlops: null,
        fp16TensorCoreTFlops: 3500.00,
        fp8TensorCoreTFlops: 7000.00,
        int8TensorCoreTOps: 7000.00,
        memorySizeGB: null,
        memoryType: "",
        memoryBandwidthGBs: null,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "",
        maxPowerW: 700
    },
    {
        id: 36,
        vendor: "NVIDIA",
        architecture: "Blackwell",
        model: "GB200 NVL72 Rack， 72 卡",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: 40.00,
        fp32TFlops: 80.00,
        fp16TensorCoreTFlops: 5000.00,
        fp8TensorCoreTFlops: 10000.00,
        int8TensorCoreTOps: 10000.00,
        memorySizeGB: 186,
        memoryType: "HBM3e",
        memoryBandwidthGBs: 8000.00,
        memoryBusWidth: "",
        interCardConnection: "NVLink 1.8TB/s",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 1200
    },
    {
        id: 37,
        vendor: "NVIDIA",
        architecture: "Blackwell",
        model: "5090",
        mainScenes: ["推理", "训练", "渲染"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: 419.00,
        fp8TensorCoreTFlops: 838.00,
        int8TensorCoreTOps: null,
        memorySizeGB: 32,
        memoryType: "GDDR7",
        memoryBandwidthGBs: 1792.00,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 575
    },
    {
        id: 38,
        vendor: "NVIDIA",
        architecture: "Blackwell",
        model: "5090D",
        mainScenes: ["推理", "训练", "渲染"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: 296.88,
        fp8TensorCoreTFlops: 594.00,
        int8TensorCoreTOps: null,
        memorySizeGB: 32,
        memoryType: "GDDR7",
        memoryBandwidthGBs: 1792.00,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 575
    },
    {
        id: 39,
        vendor: "NVIDIA",
        architecture: "Blackwell",
        model: "5080",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: 225.00,
        fp8TensorCoreTFlops: 450.00,
        int8TensorCoreTOps: null,
        memorySizeGB: 16,
        memoryType: "GDDR7",
        memoryBandwidthGBs: 960.00,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 360
    },
    {
        id: 40,
        vendor: "NVIDIA",
        architecture: "Blackwell",
        model: "5070Ti",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: 175.75,
        fp8TensorCoreTFlops: 351.50,
        int8TensorCoreTOps: null,
        memorySizeGB: 16,
        memoryType: "GDDR7",
        memoryBandwidthGBs: 896.00,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 300
    },
    {
        id: 41,
        vendor: "AMD",
        architecture: "CDNA3",
        model: "MI308X",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: 206.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: null,
        memorySizeGB: null,
        memoryType: "",
        memoryBandwidthGBs: null,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "",
        maxPowerW: null
    },
    {
        id: 42,
        vendor: "Intel",
        architecture: "Gaudi",
        model: "Gaudi2C",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: 11.10,
        fp16TensorCoreTFlops: 148.70,
        fp8TensorCoreTFlops: 297.40,
        int8TensorCoreTOps: 297.40,
        memorySizeGB: 96,
        memoryType: "HBM2e",
        memoryBandwidthGBs: null,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: null
    },
    {
        id: 43,
        vendor: "Intel",
        architecture: "消费级",
        model: "Max 1100",
        mainScenes: ["推理", "渲染"],
        type: "推理",
        fp64TFlops: 22.00,
        fp32TFlops: 22.00,
        fp16TensorCoreTFlops: 355.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 711.00,
        memorySizeGB: 48,
        memoryType: "HBM2e",
        memoryBandwidthGBs: 1200.00,
        memoryBusWidth: "",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: null
    },
    {
        id: 44,
        vendor: "腾讯",
        architecture: "紫霄v1",
        model: "ZX C100",
        mainScenes: ["推理"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 31.00,
        fp16TensorCoreTFlops: 120.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 240.00,
        memorySizeGB: 16,
        memoryType: "HBM2e",
        memoryBandwidthGBs: 819.00,
        memoryBusWidth: "",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 150
    },
    {
        id: 45,
        vendor: "腾讯",
        architecture: "紫霄v2",
        model: "ZX C200（燧原 S60）",
        mainScenes: ["推理"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 32.00,
        fp16TensorCoreTFlops: 131.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 262.00,
        memorySizeGB: 48,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 672.00,
        memoryBusWidth: "",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 300
    },
    {
        id: 46,
        vendor: "华为",
        architecture: "昇腾",
        model: "910B1 arm 版本",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: null,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: null,
        memorySizeGB: null,
        memoryType: "",
        memoryBandwidthGBs: null,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "",
        maxPowerW: null
    },
    {
        id: 47,
        vendor: "华为",
        architecture: "昇腾",
        model: "910B2",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: 99.00,
        fp16TensorCoreTFlops: 376.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 700.00,
        memorySizeGB: 64,
        memoryType: "HBM2e",
        memoryBandwidthGBs: 1600.00,
        memoryBusWidth: "",
        interCardConnection: "392GB/s全互联",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 450
    },
    {
        id: 48,
        vendor: "华为",
        architecture: "昇腾",
        model: "910B3",
        mainScenes: ["推理"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: 313.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: null,
        memorySizeGB: 64,
        memoryType: "HBM2e",
        memoryBandwidthGBs: 1600.00,
        memoryBusWidth: "",
        interCardConnection: "392GB/s全互联",
        pcieConnection: "",
        maxPowerW: null
    },
    {
        id: 49,
        vendor: "华为",
        architecture: "昇腾",
        model: "910B4",
        mainScenes: ["推理"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: 280.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: null,
        memorySizeGB: 64,
        memoryType: "HBM2e",
        memoryBandwidthGBs: 1600.00,
        memoryBusWidth: "",
        interCardConnection: "392GB/s全互联",
        pcieConnection: "",
        maxPowerW: null
    },
    {
        id: 50,
        vendor: "华为",
        architecture: "昇腾",
        model: "910C",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: null,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: null,
        memorySizeGB: 128,
        memoryType: "",
        memoryBandwidthGBs: null,
        memoryBusWidth: "",
        interCardConnection: "784GB/s Switch",
        pcieConnection: "",
        maxPowerW: null
    },
    {
        id: 51,
        vendor: "天数",
        architecture: "天数智芯",
        model: "天垓 100",
        mainScenes: ["训练"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: 32.00,
        fp16TensorCoreTFlops: 128.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 256.00,
        memorySizeGB: 32,
        memoryType: "HBM2",
        memoryBandwidthGBs: null,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 250
    },
    {
        id: 52,
        vendor: "天数",
        architecture: "天数智芯",
        model: "智铠100",
        mainScenes: ["推理"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 24.00,
        fp16TensorCoreTFlops: 96.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 192.00,
        memorySizeGB: 32,
        memoryType: "HBM2e",
        memoryBandwidthGBs: null,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 150
    },
    {
        id: 53,
        vendor: "海光",
        architecture: "DCU",
        model: "深算一号 Z100",
        mainScenes: ["推理"],
        type: "推理",
        fp64TFlops: 10.10,
        fp32TFlops: 12.20,
        fp16TensorCoreTFlops: 24.50,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 49.20,
        memorySizeGB: 32,
        memoryType: "HBM2",
        memoryBandwidthGBs: null,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 280
    },
    {
        id: 54,
        vendor: "海光",
        architecture: "DCU",
        model: "深算二号 K100",
        mainScenes: ["推理"],
        type: "推理",
        fp64TFlops: 24.50,
        fp32TFlops: 24.50,
        fp16TensorCoreTFlops: 100.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 200.00,
        memorySizeGB: 64,
        memoryType: "GDDR6",
        memoryBandwidthGBs: null,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 300
    },
    {
        id: 55,
        vendor: "海光",
        architecture: "DCU",
        model: "深算二号（AI） K100-AI",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: 49.00,
        fp16TensorCoreTFlops: 196.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 393.00,
        memorySizeGB: 64,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 896.00,
        memoryBusWidth: "",
        interCardConnection: "",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 400
    },
    {
        id: 56,
        vendor: "海光",
        architecture: "DCU",
        model: "深算三号 BW1000",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: 480.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: null,
        memorySizeGB: 64,
        memoryType: "HBM2e",
        memoryBandwidthGBs: 1800.00,
        memoryBusWidth: "",
        interCardConnection: "448GB/s Switch",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: null
    },
    {
        id: 57,
        vendor: "寒武纪",
        architecture: "MLU",
        model: "MLU370-X9",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: 36.00,
        fp16TensorCoreTFlops: 144.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 384.00,
        memorySizeGB: 96,
        memoryType: "",
        memoryBandwidthGBs: null,
        memoryBusWidth: "",
        interCardConnection: "200GB/s 4卡Bridge",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 250
    },
    {
        id: 58,
        vendor: "寒武纪",
        architecture: "MLU",
        model: "MLU590-X8",
        mainScenes: ["推理"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: 312.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: null,
        memorySizeGB: 96,
        memoryType: "",
        memoryBandwidthGBs: 2700.00,
        memoryBusWidth: "",
        interCardConnection: "MLU-LINK 371.9GB/s全互联",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: null
    },
    {
        id: 59,
        vendor: "沐曦",
        architecture: "曦云",
        model: "曦云C500",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: null,
        fp16TensorCoreTFlops: 238.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: null,
        memorySizeGB: 64,
        memoryType: "HBM2e",
        memoryBandwidthGBs: 1500.00,
        memoryBusWidth: "",
        interCardConnection: "896GB/s全互联",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: null
    },
    {
        id: 60,
        vendor: "摩尔线程",
        architecture: "MTT",
        model: "S4000",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: 32.00,
        fp16TensorCoreTFlops: 128.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 256.00,
        memorySizeGB: 48,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 768.00,
        memoryBusWidth: "",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: 450
    },
    {
        id: 61,
        vendor: "昆仑芯",
        architecture: "昆仑芯二代",
        model: "R200",
        mainScenes: ["推理"],
        type: "推理",
        fp64TFlops: null,
        fp32TFlops: 32.00,
        fp16TensorCoreTFlops: 128.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 256.00,
        memorySizeGB: 16,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 512.00,
        memoryBusWidth: "",
        interCardConnection: "不支持",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 150
    },
    {
        id: 62,
        vendor: "昆仑芯",
        architecture: "昆仑芯二代",
        model: "R480-X8",
        mainScenes: ["训练", "推理"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: 32.00,
        fp16TensorCoreTFlops: 128.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 256.00,
        memorySizeGB: 32,
        memoryType: "GDDR6",
        memoryBandwidthGBs: 512.00,
        memoryBusWidth: "",
        interCardConnection: "200GB/s 类似V100",
        pcieConnection: "PCIe Gen4x16: 64GB/s",
        maxPowerW: 187.5
    },
    {
        id: 63,
        vendor: "昆仑芯",
        architecture: "昆仑芯三代",
        model: "P800",
        mainScenes: ["训练"],
        type: "训练",
        fp64TFlops: null,
        fp32TFlops: 19.50,
        fp16TensorCoreTFlops: 320.00,
        fp8TensorCoreTFlops: null,
        int8TensorCoreTOps: 624.00,
        memorySizeGB: 96,
        memoryType: "HBM2e",
        memoryBandwidthGBs: null,
        memoryBusWidth: "",
        interCardConnection: "400GB/s 类似V100",
        pcieConnection: "PCIe Gen5x16 128GB/s",
        maxPowerW: null
    }
];

// 导出数据（如果使用模块化）
if (typeof module !== 'undefined' && module.exports) {
    module.exports = gpuData;
}